### ISSUE TITLE
Feature Request: Implement NoVersioning for GCP buckets

### ISSUE THREAD

**Issue by eadderley** [camptocamp/terraboard#285]
We're trying to use terraboard to inspect our absolutely massive state files. Unfortunately, to go along with their absolutely massive size, they're versioned going back 4 years in some cases, with near-daily versions. 

This makes Terraboard tragically unusable in our case. 

It'd be super cool if you all could implement `NoVersioning` for GCP bucket lookups. :slightly_smiling_face:

**Comment by hbollon** [comment]
Indeed, it could be really nice to have. I will have a look

**Comment by hbollon** [comment]
I pushed a commit to support _noLocks_ and _noVersioning_ features with others providers than AWS, however I don't have any GCP resources to test it. Can you build an image using the `integration-tests` branch and give it a try please? :pray:

**Comment by eadderley** [comment]
@hbollon Amazing! Will make time for this next week.

**Comment by eadderley** [comment]
Well, my previous comment was obviously a fib. I managed to steal some time during this sprint to test it. It seems to be working fine! Will verify tomorrow and then have a teammate double check.  

Thanks for this!

**Comment by hbollon** [comment]
Glad to hear that ! :smile: 
I wait your final validation to merge this :+1:

**Comment by eadderley** [comment]
Well, unfortunately it doesn't seem to be loading any versions. I took a brief look at the code and suspect the offending line is [this one](https://github.com/camptocamp/terraboard/blob/f59bb70577b7af1347ef6b2cbcbe18d4d1f9f3b0/state/gcp.go#L220-L221), with the time.Now(). Not sure how AWS is handling that, maybe the API automatically pulls the nearest timestamp to it, but I don't think GCP's works the same way.

**Comment by eadderley** [comment]
Disregard, ID-10-T error. set `no-sync: false` and it's populating

**Comment by eadderley** [comment]
Yeah, I don't think that's done it. 
![Selection_117](https://github.com/camptocamp/terraboard/assets/25034184/8fc4f075-b957-42d9-8753-220cf1acd414)

```
log:
  level: error
  format: json

database:
  host: db
  port: 5432
  user: gorm
  password: mypassword
  name: gorm
  no-sync: false
  sslmode: disable

gcp:
  - gcs-bucket:
      - up-terraform-tfstate-aa3c
    gcp-sa-key-path: /opt/build/up-terraform-seed-9439-097878bac0b4.json
    no-versioning: true
```

Also tried with env var `TERRABOARD_NO_VERSIONING: true` in docker-compose.yml.
