### ISSUE TITLE
Using terraform with workspaces, not seeing the states.

### ISSUE THREAD

**Issue by one1zero1one** [camptocamp/terraboard#42]
When running a terraform workspaces, "env:/workspace" folders gets created in the s3, however terraboard doesn't pick that up, even when empty AWS_KEY_PREFIX and AWS_FILE_EXTENSION. 

The workaround that seems to do it for me was to comment out the if in the GetStates() of  s3.go

```
for _, obj := range result.Contents {
//		if strings.HasSuffix(*obj.Key, ".tfstate") {
			keys = append(keys, *obj.Key)
//		}
	}
```
and rebuild, then all the possible folders and states files (regardless of extension) show up in the gui - which is the behaviour I needed. Not sure why or how - my go knowledge and time to debug is limited. However since terraboard is an awesome tool (big thanks), thought I shared my finding.

**Comment by raphink** [comment]
Hello,

You must be using an old version which did not support `AWS_FILE_EXTENSION`, as suggested by the edit you're doing. The current code reads:

```go
	for _, obj := range result.Contents {
		if strings.HasSuffix(*obj.Key, fileExtension) {
			keys = append(keys, *obj.Key)
		}
	}
```

which uses honors the `AWS_FILE_EXTENSION` setting.

Could you try again making sure to use the latest release (currently 0.14.3) please?

**Comment by one1zero1one** [comment]
Hey,  

I've rebuild the latest release, cleaned up the docker volume.  My compose file looks like this.

```
---
version: '3'
services:
  terraboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: camptocamp/terraboard:devel
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      BASE_URL: /terraboard/
      DB_PASSWORD: mypassword
      AWS_DYNAMODB_TABLE: ${AWS_DYNAMODB_TABLE}
      AWS_KEY_PREFIX:
      AWS_FILE_EXTENSION:
      TERRABOARD_LOG_LEVEL: debug
      TERRABOARD_LOGOUT_URL: /oauth2/sign_in
    links:
      - "db"
    ports:
      - 8080:8080
    volumes:
      - ./static:/static:ro

  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: gorm
    volumes:
      - tb-data:/var/lib/postgresql/data

volumes:
  tb-data: {}
```

When I run it, it doesn't seem to get anything form S3.

```
Attaching to terraboard_db_1, terraboard_terraboard_1
db_1          | LOG:  database system was shut down at 2017-12-12 13:46:47 UTC
db_1          | LOG:  MultiXact member wraparound protections are now enabled
terraboard_1  | time="2017-12-12T13:46:50Z" level=info msg="Terraboard v0.14.3 is starting..."
db_1          | LOG:  database system is ready to accept connections
db_1          | LOG:  autovacuum launcher started
terraboard_1  | time="2017-12-12T13:46:50Z" level=info msg=Automigrate
terraboard_1  | time="2017-12-12T13:46:50Z" level=info msg="Refreshing DB from S3"
terraboard_1  |
terraboard_1  | (/go/src/github.com/camptocamp/terraboard/db/db.go:237)
terraboard_1  | [2017-12-12 13:46:51]  [1.48ms]  SELECT states.path, versions.version_id FROM "states" JOIN versions ON versions.id = states.version_id
terraboard_1  | [0 rows affected or returned ]
terraboard_1  | time="2017-12-12T13:47:51Z" level=info msg="Refreshing DB from S3"
terraboard_1  |
terraboard_1  | (/go/src/github.com/camptocamp/terraboard/db/db.go:237)
terraboard_1  | [2017-12-12 13:47:52]  [0.88ms]  SELECT states.path, versions.version_id FROM "states" JOIN versions ON versions.id = states.version_id
terraboard_1  | [0 rows affected or returned ]
```

Now, if I take out that if, clean docker volumes/images, rebuild, and run the exact same compose file, it imeadiatly starts picking up all states from all folders in s3.

```
Starting terraboard_terraboard_1 ... done
Attaching to terraboard_db_1, terraboard_terraboard_1
db_1          | LOG:  database system was shut down at 2017-12-12 13:57:31 UTC
db_1          | LOG:  MultiXact member wraparound protections are now enabled
terraboard_1  | time="2017-12-12T13:57:37Z" level=info msg="Terraboard v0.14.3 is starting..."
db_1          | LOG:  database system is ready to accept connections
terraboard_1  | time="2017-12-12T13:57:37Z" level=info msg=Automigrate
db_1          | LOG:  autovacuum launcher started
terraboard_1  | time="2017-12-12T13:57:37Z" level=info msg="Refreshing DB from S3"
terraboard_1  |
terraboard_1  | (/go/src/github.com/camptocamp/terraboard/db/db.go:237)
terraboard_1  | [2017-12-12 13:57:38]  [1.26ms]  SELECT states.path, versions.version_id FROM "states" JOIN versions ON versions.id = states.version_id
terraboard_1  | [0 rows affected or returned ]
terraboard_1  |
terraboard_1  | (/go/src/github.com/camptocamp/terraboard/db/db.go:105)
terraboard_1  | [2017-12-12 13:57:38]  [4.41ms]  SELECT * FROM "versions"  WHERE ("versions"."version_id" = 'JT9JU4zEgrwE5b6jSPIyoiB_.6tKk95O') AND ("versions"."last_modified" = '2017-12-11 17:05:11') ORDER BY "versions"."id" ASC LIMIT 1
terraboard_1  | [0 rows affected or returned ]
terraboard_1  |
terraboard_1  | (/go/src/github.com/camptocamp/terraboard/db/db.go:105)
terraboard_1  | [2017-12-12 13:57:38]  [0.94ms]  INSERT INTO "versions" ("version_id","last_modified") VALUES ('JT9JU4zEgrwE5b6jSPIyoiB_.6tKk95O','2017-12-11 17:05:11') RETURNING "versions"."id"
terraboard_1  | [1 rows affected or returned ]
terraboard_1  | time="2017-12-12T13:57:38Z" level=info msg="Retrieving state from S3" path="env:/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx" version_id=JT9JU4zEgrwE5b6jSPIyoiB_.6tKk95O
terraboard_1  |
```

My intuition is that there's something around the `AWS_FILE_EXTENSION` setting, that it comes somehow not empty, so I tried various things in docker compose but no luck. I'm okay with the workaround (since my use case involves a ton of terraform workspaces), however no idea why this behavour.
